### ISSUE TITLE
Suggesting optimised meetings

### ISSUE THREAD

**Issue by fikretellek** [bkarimii/AppOintment-projet#35]
Suggested meeting section should appear on the top of the page to show the user best meeting times for different criteria's.
table should be sorted by selected option from dropdown.

rank meeting by dropdown
- average 
- median
- ...

best meeting time card (information, each attendee and what time they should travel, have a copy button of attendee travel info)

**Comment by OracPrime** [comment]
I think this is replace by #39 so closing it

**Comment by OracPrime** [comment]
I think this is replace by #39 so closing it
