### ISSUE TITLE
Delete button in the form doesn't work

### ISSUE THREAD

**Issue by bkarimii** [bkarimii/AppOintment-projet#69]
### Describe the bug

When the delete buttons for attendees in the form don't work, clicking on each one triggers a fetch and redirects to the results page.

### Checklist

- [ ] I have recreated the issue in the vanilla starter kit _(this is a template repo, some issues may be related to code or configuration that has been added outside the starter kit)_.
- [ ] I am using a supported version of Node _(at least 20.9)_ and npm _(not Yarn)_.
- [ ] I have installed the correct dependencies _(run `npm ci` if you're unsure, this will clear `node_modules/` and install based on the `package-lock.json`)_.

**Comment by OracPrime** [comment]
Confirmed fixed
