### ISSUE TITLE
Json Format

### ISSUE THREAD

**Issue by bkarimii** [bkarimii/AppOintment-projet#9]
## Story

- **As a**  Developer 

- **I Want** to know the format of the json file 

- **So That** I can work between front-end and back-end

## Acceptance Criteria

1. Given .............
   - When .............
   - Then .............
2. Given .............
   - When .............
   - Then .............

## Implementation Notes

1. Meeting station
2. Attendees stations
3. Arriving date
4. Earliest start time
5. Latest start time
Must be created in a json format

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by fikretellek** [comment]
{meetingStation: "string", meetingDate: "1111-11-11", earliestStartTime: "11:11", latestStartTime: "11:11", attendees: [array]}

ex:
{meetingStation: 'AUR', meetingDate: '1111-11-11', earliestStartTime: '11:11', latestStartTime: '11:11', attendees: ['ABA', 'AGL', 'ACC']}
